FROM node:20-alpine

WORKDIR /app

# Dependências
COPY package.json pnpm-lock.yaml ./

RUN npm install -g pnpm

RUN pnpm install

# Copia projeto
COPY . .

# Prisma
RUN npx prisma generate

# Build
RUN pnpm build

EXPOSE 3333

CMD ["pnpm", "dev"]